version: '3.8'
services:
  api:
    image: psyart_23
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    ports:
      - 3000:3000
    command: npm run start:dev
    environment:
      MONGODB_URI: ${MONGODB_URI}
      AUTH: ${AUTH}
      DB_NAME: ${DB_NAME}
    networks:
      - psyart

networks:
  psyart:
