version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    networks:
      - psyart

  production_api:
    image: srdjankljajo/psyart_23
    deploy:
      replicas: 2
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build:
      context: .
    ports:
      - 3000:80
    env_file:
      - .env
    networks:
      - psyart

networks:
  psyart:
